### ISSUE TITLE
All processes try to remove tmp dir

### ISSUE THREAD

**Issue by matschaffer** [stellar/stellar_core_commander#6]
Ran into this today. Looks like when running multiple processes the first one might clean up the tmp dir before the last one finishes shutting down:

```
cleaning up 2 processes
/Users/mat/stellar/stellar_core_commander/lib/stellar_core_commander/process.rb:180:in `chdir': No such file or directory @ dir_chdir - /var/folders/5t/dcwhdrzs4mn8t7m9vwtw9_bc0000gn/T/scc20150603-20726-18p7np4 (Errno::ENOENT)
	from /Users/mat/stellar/stellar_core_commander/lib/stellar_core_commander/process.rb:180:in `run_cmd'
	from /Users/mat/.rvm/gems/ruby-2.2.2/gems/contracts-0.9/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/mat/.rvm/gems/ruby-2.2.2/gems/contracts-0.9/lib/contracts.rb:371:in `call_with'
	from /Users/mat/.rvm/gems/ruby-2.2.2/gems/contracts-0.9/lib/contracts/decorators.rb:182:in `block in common_method_added'
	from /Users/mat/stellar/stellar_core_commander/lib/stellar_core_commander/docker_process.rb:48:in `running?'
	from /Users/mat/.rvm/gems/ruby-2.2.2/gems/contracts-0.9/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/mat/.rvm/gems/ruby-2.2.2/gems/contracts-0.9/lib/contracts.rb:371:in `call_with'
	from /Users/mat/.rvm/gems/ruby-2.2.2/gems/contracts-0.9/lib/contracts/decorators.rb:182:in `block in common_method_added'
	from /Users/mat/stellar/stellar_core_commander/lib/stellar_core_commander/docker_process.rb:60:in `shutdown'
	from /Users/mat/.rvm/gems/ruby-2.2.2/gems/contracts-0.9/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/mat/.rvm/gems/ruby-2.2.2/gems/contracts-0.9/lib/contracts.rb:371:in `call_with'
	from /Users/mat/.rvm/gems/ruby-2.2.2/gems/contracts-0.9/lib/contracts/decorators.rb:182:in `block in common_method_added'
	from /Users/mat/stellar/stellar_core_commander/lib/stellar_core_commander/docker_process.rb:67:in `cleanup'
	from /Users/mat/.rvm/gems/ruby-2.2.2/gems/contracts-0.9/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/mat/.rvm/gems/ruby-2.2.2/gems/contracts-0.9/lib/contracts.rb:371:in `call_with'
	from /Users/mat/.rvm/gems/ruby-2.2.2/gems/contracts-0.9/lib/contracts/decorators.rb:182:in `block in common_method_added'
	from /Users/mat/stellar/stellar_core_commander/lib/stellar_core_commander/commander.rb:67:in `each'
	from /Users/mat/stellar/stellar_core_commander/lib/stellar_core_commander/commander.rb:67:in `cleanup'
	from /Users/mat/stellar/stellar_core_commander/lib/stellar_core_commander/commander.rb:73:in `block in cleanup_at_exit!'
```

**Comment by matschaffer** [comment]
Oh, actually looks like this specifically happens when using `./b/scc -r examples/simple_payment.rb -p docker`

Could be that recipe needs updating for the new case. Will investigate.
